spring:
  application:
    name: web-admin-feign
  zipkin:
    base-url: http://localhost:9411

  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-feign
      label: master
      profile: dev
